# Generated by Django 5.0.7 on 2024-07-13 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instaphish', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accounts',
            options={'verbose_name': 'Account', 'verbose_name_plural': 'Accounts'},
        ),
        migrations.AddField(
            model_name='accounts',
            name='is_insta',
            field=models.BooleanField(default=True),
        ),
    ]
